apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    #- host: https://178.128.137.82.sslip.io
    http:
      paths:
        - path: /api/users/?(.*)
          pathType: Prefix
          backend:
            service:
              name: auth-srv
              port:
                number: 3000
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: http
  externalIPs:
    - 178.128.137.82
